### ISSUE TITLE
Save downloaded image's id to a txtfile

### ISSUE THREAD

**Issue by kajeagentspi** [Thammus/instaloader#21]
Beneficial for those that upload the files to cloud.

Much like what youtube-dl does

**Comment by kajeagentspi** [comment]
Also someone's ig with cars gets downloaded

**Comment by Thammus** [comment]
Hi kajeagentspi,

sorry for my long responding time. If this issue is still relevant for you, can you please clarify which kind of id should be stored? Do you mean the media id (e.g. `1472633142371640410`) or the base64 encoded shortcode of the media id (e.g. `BRv2Apnh2Ra`) which is used in Instagram's URLs? Should these ids of all downloaded images simply be stored in a text file line by line? I'm curious how this could be used to upload the files to a cloud.

Yours sincerely,
Thammus

**Comment by aandergr** [comment]
The newly added option `--filename-pattern` allows to encode the node's shortcode in the file name, e.g. by passing `--filename-pattern={shortcode}`.
