### ISSUE TITLE
Preventing text files from being saved

### ISSUE THREAD

**Issue by MatthieuBonenfant** [Thammus/instaloader#25]
I have not figured yet how to prevent the text files from being saved along the images. Maybe we could have a "--no-text-file" function as well?

Thanks

**Comment by aandergr** [comment]
117124d adds the option `--no-captions` which prevents Instaloader from saving the caption text files. However, it is still in the experimental branch `v3-dev`.
```
$ pip3 install --upgrade git+https://github.com/Thammus/instaloader@v3-dev
$ instaloader --no-captions ...
```

I personally do not consider this an important feature. On modern filesystems, the caption files usually need 0 bytes of space, since most of them can be inlined into their inode. Furthermore, in case they are absolutely not desired, a simple `rm *.txt` would match and delete them.

Happy instaloading!
Alex

**Comment by MatthieuBonenfant** [comment]
In windows, I have been searching and deleting 70,000 text files a day takes a lot of resources and a few minutes. Thanks for implementing.
