### ISSUE TITLE
Errors occured: Unable to get owner name of post BXwcNmmDkok: 404 -- using 'UNKNOWN'.

### ISSUE THREAD

**Issue by MatthieuBonenfant** [Thammus/instaloader#36]
I have not seen that one before. I am on 2.2.3

[21428] #starwars #starwars/antonini.art.dzny_2017-08-12_10-54-15.jpg exists

Errors occured:
Unable to get owner name of post BXwcNmmDkok: 404 -- using 'UNKNOWN'.
Download hashtag #starwars: 404 when accessing https://instagram.fymy1-1.fna.fbcdn.net/t51.2885-15/e35/20686986_1636403346432445_1785624497169104896_n.jpg.

**Comment by Thammus** [comment]
This is not a bug. After finishing its tasks Instaloader provides a summary of all errors that occurred. The reported ones can happen if someone deletes his/her profile while Instaloader is trying to download an associated post. 
By the way, some strings of these error messages only appear on the version from the v3-dev branch at the moment. This means you were not using version 2.2.3 as stated. But this is quite fine since it helps us further improving the future version.

**Comment by MatthieuBonenfant** [comment]
sorry, you are right I was in 3-dev while this error occured. I tried 2.2.3 but it did not have the --no-caption yet so I switched back to 3-dev. Good to know it is a report. Not an error. Maybe write Error Report Summary to avoid confusion.

**Comment by MatthieuBonenfant** [comment]
... and a confirmation the script has completed and not crashed.

**Comment by aandergr** [comment]
Thanks for reporting this and for testing our `v3-dev` version. 

However, it seems Instaloader worked just fine in this case. Sorry if our program may have caused confusion. If nonfatal errors occur, they are printed to console and recorded to be printed again before Instaloader terminates, with a preceeding `Errors occured` message. If an error occurs that cannot be recovered, it is printed with a preceeding `Fatal error:` message, and Instaloader exits immediately with a non-zero exit status. (At least that's how Instaloader _should_ behave)
