### ISSUE TITLE
Feature Request: Store local files with UTC time in file names

### ISSUE THREAD

**Issue by Zanadou** [Thammus/instaloader#69]
I noticed that instaloader stores local files offset to the local time zone of the computer. Perhaps this is done at Instagram's end.

However, this can cause issues with computers that move time zones often (i.e. laptops) and/or DST zone changes: it causes the time encoded in the filenames to "de-sync" and then prevent the ---fast-update flag from working properly. ie. instaloader will just download the entire account from scratch all over again with the new time zone offset.

Is it possible to have the file names saved in robust UTC/GMT/Zulu time, instead? If it is an issue at Instgram's end perhaps a manual time zone offset setting flag could be introduced.

**Comment by aandergr** [comment]
My latest commit, e6be017, introduces a new filename-pattern `{date_utc}` which encodes the creation time relative to UTC. It can be used with `--filename-pattern={date_utc}`.

Thanks for this suggestion. It is much more reasonable to encode the time as UTC, I guess this was simply not considered when the logic for filenames and fast-update was implemented, which already was at the very first version of Instaloader.

However, we cannot yet set this the default, since with `--fast-update` it would break (rather double-download) the archives of users unaware of that change. I relabel this issue as bug, since it should be considered as such, and leave it open until we have implemented a proper solution.

During the meantime, I recommend consistently using the new `instaloader --filename-pattern={date_utc}` in situations where time zones change often.

Happy Instaloading!
Alex

**Comment by MatthieuBonenfant** [comment]
Neato! User experience first! I guess it affected a few more of us when we changed to Daylight Saving time without realizing it. Better standardize to UTC.

**Comment by Thammus** [comment]
My latest commits to the [bug_69_fix](/Thammus/instaloader/tree/bug_69_fix) branch, 3654d6b and 9b11ca1, ensure the default usage of UTC encoded dates in filenames. Files named according to the old convention get recognized in order to keep the `--fast-update` switch working with older collections, excluding geotags and the post metadata JSON files. The files containing comments get renamed to the new format when touched. Caption files are only renamed, if they get updated. Stored picture files do not get renamed at all.

**Comment by Deleora** [comment]
> My latest commit, [e6be017](https://github.com/instaloader/instaloader/commit/e6be0179b7ed408cb621d4261dd2207e30353f1a), introduces a new filename-pattern `{date_utc}` which encodes the creation time relative to UTC. It can be used with `--filename-pattern={date_utc}`.
> 
> Thanks for this suggestion. It is much more reasonable to encode the time as UTC, I guess this was simply not considered when the logic for filenames and fast-update was implemented, which already was at the very first version of Instaloader.
> 
> However, we cannot yet set this the default, since with `--fast-update` it would break (rather double-download) the archives of users unaware of that change. I relabel this issue as bug, since it should be considered as such, and leave it open until we have implemented a proper solution.
> 
> During the meantime, I recommend consistently using the new `instaloader --filename-pattern={date_utc}` in situations where time zones change often.
> 
> Happy Instaloading!
> Alex

Is there a way to store posts, stories, etc in local time as well?
