### ISSUE TITLE
account requires login

### ISSUE THREAD

**Issue by theophileernoult** [Thammus/instaloader#79]
hi i want to download photos from a private account i do not follow.
Is this possible?
Because each time i try, i login, my session is stored, and then i launch "instaloader [profile_name]" and it says : 'this profile requires login'.

What am i doing wrong ? thank you in advance 👍

**Comment by aandergr** [comment]
Hi.

Instaloader should say `Profile %s: private but not followed`, rather than `profile %s requires login`. You have to pass `--login USERNAME` option always to access Instagram non-anonymously, regardless of whether you previously created a session file or not.

Instaloader does not download photos from a private account if it is not followed by the user, and we are not planning to work on or publish such a feature.

Anyway, happy Instaloading!
Alex

**Comment by theophileernoult** [comment]
okay, thank you for the fast answer :)
